<a href="https://colab.research.google.com/github/Sainithinreddyk/SaiNithinReddy_INFO5731_-Spring2023/blob/main/In_class_exercise_03_SaiNithinReddy_Koppula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (2/28/2023, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [243]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

During the COVID-19 pandemic many people ordered the oximeters and Sphygmomanometer to track the health condition and ensure that their health is stable and in this I am going to take one of the Sphygmomanometer
from amazon and track the reviews and classify the text. The features that might be useful for building a good model are
Number of sentences is usefull in finding out the how many snetences are present in the list
Number of words is usefull in finding out the how many words are present in the list
Number of characters is usefull in finding out the how many characters are present in the list
Number of special characters is usefull in finding out the number of special characters that are present in the list
I want to apply the text categorization method to gauge the emotions expressed in product reviews. The parts of speech used in the text can be used to determine
each statement's main structure, purposes, and uses.
I have remoced all the stop words in the sentence to reduce the noice and improve the efficiency
I will classify each sentence in the text according to the part of speech to which it belongs.
 
I have collected the data from amazon and the url is "https://www.amazon.com/product-reviews/B0B9HGV6JB/ref=acr_dp_hist_5?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews#reviews-filter-bar"

'''

'\nPlease write you answer here:\n\nDuring the COVID-19 pandemic many people ordered the oximeters and Sphygmomanometer to track the health condition and ensure that their health is stable and in this I am going to take one of the Sphygmomanometer\nfrom amazon and track the reviews and classify the text. The features that might be useful for building a good model are\nNumber of sentences is usefull in finding out the how many snetences are present in the list\nNumber of words is usefull in finding out the how many words are present in the list\nNumber of characters is usefull in finding out the how many characters are present in the list\nNumber of special characters is usefull in finding out the number of special characters that are present in the list\nI want to apply the text categorization method to gauge the emotions expressed in product reviews. The parts of speech used in the text can be used to determine\neach statement\'s main structure, purposes, and uses.\nI have remoced all the stop words in the sentence to reduce the noice and improve the efficiency\nI will classify each sentence in the text according to the part of speech to which it belongs.\n \nI have collected the data from amazon and the url is "https://www.amazon.com/product-reviews/B0B9HGV6JB/ref=acr_dp_hist_5?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews#reviews-filter-bar"\n\n'

Question 2 (10 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [244]:
# You code here (Please add comments in the code):

#Intially I have loaded all the necessary libraries
from bs4 import BeautifulSoup
import requests
import urllib.request
import re
import pandas as pd

In [245]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.amazon.com/product-reviews/B0B9HGV6JB/ref=acr_dp_hist_5?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews#reviews-filter-bar'

headers = {'User-Agent': 'Mozilla/5.0'}

titles = []
text = []

for pg in range(1, 150):
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    titles += [title.get_text().strip() for title in soup.find_all('a', class_='review-title-content')]
    text += [review.get_text().strip() for review in soup.find_all('span', class_='review-text-content')]

In [246]:
# Tile column contains the title and reciew contains the text
data = {'Title': titles, 'Review': text}
raw_data = pd.DataFrame(data)
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   90 non-null     object
 1   Review  90 non-null     object
dtypes: object(2)
memory usage: 1.5+ KB

In [247]:
raw_data.head()

,Title,Review
0,Accurate and easy to use,This is well made and a great price. I know it...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...
2,Easy to use,I have tried a few blood pressure devices all ...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...

**SENTENCE COUNT**

In [248]:
#Counting the number of sentences in each review
raw_data['Number  of sentences'] = raw_data['Review'].apply(lambda y: len(str(y).split(".")))
raw_data.head()

,Title,Review,Number of sentences
0,Accurate and easy to use,This is well made and a great price. I know it...,5
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3
2,Easy to use,I have tried a few blood pressure devices all ...,4
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4

**WORD COUNT**

In [249]:
#Countong the number of words in a review
raw_data['Number of Words'] = raw_data['Review'].apply(lambda y: len(str(y).split(" ")))
raw_data.head()

,Title,Review,Number of sentences,Number of Words
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63
2,Easy to use,I have tried a few blood pressure devices all ...,4,43
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48

**CHARECTER COUNT**

In [250]:
#Counting the number of charecters in each review
raw_data['Number of Charecters'] = raw_data['Review'].str.len()
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240

**SPECIAL CHARECTERS COUNT**

In [251]:
#Counting the number of special charecters
def spchar(x):
    red = 0
    for i in range(len(x)):
        if not((x[i].isalpha()) and (x[i].isdigit())):
            red = red + 1
    return red

raw_data['Number of special charecters'] = raw_data['Review'].apply(lambda y: spchar(y))
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240

**NUMERIC COUNT**

In [252]:
raw_data['Num of num'] = raw_data['Review'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0

**COLUMN NAMES**

In [253]:
print(raw_data.columns)

Index(['Title', 'Review', 'Number  of sentences', 'Number of Words',
       'Number of Charecters', 'Number of special charecters', 'Num of num'],
      dtype='object')

**DROPPING THE UNNECESSARY COLUMNS**

In [254]:
"""# Define a list of columns to keep
cols_to_keep = ['Title', 'Review', 'Modified_review']

# Drop all other columns
raw_data = raw_data.drop(columns=[col for col in raw_data.columns if col not in cols_to_keep])
raw_data.head()"""

"# Define a list of columns to keep\ncols_to_keep = ['Title', 'Review', 'Modified_review']\n\n# Drop all other columns\nraw_data = raw_data.drop(columns=[col for col in raw_data.columns if col not in cols_to_keep])\nraw_data.head()"

**REMOVING ALPHANUMERIC**

In [255]:
raw_data['Modified_review'] = raw_data['Review'].apply(lambda x: x.replace('[^\w\s]',''))
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,This is well made and a great price. I know it...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,Actually we tried a wrist blood pressure monit...
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,I have tried a few blood pressure devices all ...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,Replaced my wrist bp monitor and find this to ...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,My doctor requested that I take my bp every da...

**REMOVING NUMERIC DATA**

In [256]:
raw_data['Modified_review'] = raw_data['Modified_review'].str.replace('\d', '')
raw_data.head()

<ipython-input-256-b03feb6281e8>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  raw_data['Modified_review'] = raw_data['Modified_review'].str.replace('\d', '')

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,This is well made and a great price. I know it...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,Actually we tried a wrist blood pressure monit...
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,I have tried a few blood pressure devices all ...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,Replaced my wrist bp monitor and find this to ...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,My doctor requested that I take my bp every da...

**REMOVING SPECIAL CHARECTERS**

In [257]:

raw_data["Modified_review"] = raw_data['Modified_review'].apply(lambda t : ''.join(re.sub(r"[^a-zA-Z0-9]+", ' ', ch) for ch in t))
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,This is well made and a great price I know it...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,Actually we tried a wrist blood pressure monit...
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,I have tried a few blood pressure devices all ...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,Replaced my wrist bp monitor and find this to ...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,My doctor requested that I take my bp every da...

**COVERTING STRING TO LOWER CASE**

In [258]:
raw_data['Modified_review'] = raw_data['Modified_review'].apply(lambda text: " ".join(word.lower() for word in text.split()))
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,this is well made and a great price i know it ...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,actually we tried a wrist blood pressure monit...
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,i have tried a few blood pressure devices all ...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,replaced my wrist bp monitor and find this to ...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,my doctor requested that i take my bp every da...

**REMOVING STOP WORDS**

In [259]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = stopwords.words('english')
raw_data['Modified_review'] = raw_data['Modified_review'].apply( lambda text : " ".join(w for w in text.split() if w not in stop_words) )
raw_data.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,well made great price know accurate know eaten...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,actually tried wrist blood pressure monitor ac...
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,tried blood pressure devices returned one simp...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,replaced wrist bp monitor find accurate easy r...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,doctor requested take bp every day month reaso...

**LEMATIZZING**

In [260]:
import nltk
nltk.download('omw-1.4')
from textblob import Word
nltk.download('wordnet')
raw_data['Modified_review'] = raw_data['Modified_review'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
raw_data.head()

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,well made great price know accurate know eaten...
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,actually tried wrist blood pressure monitor ac...
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,tried blood pressure device returned one simpl...
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,replaced wrist bp monitor find accurate easy r...
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,doctor requested take bp every day month reaso...

**POS OF EACH WORD IN REVIEW**

In [261]:
nltk.download('averaged_perceptron_tagger')
from nltk import pos_tag
raw_data['POS_Review'] = raw_data['Modified_review'].str.split().map(pos_tag)
raw_data.head()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review,POS_Review
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,well made great price know accurate know eaten...,"[(well, RB), (made, RB), (great, JJ), (price, ..."
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,actually tried wrist blood pressure monitor ac...,"[(actually, RB), (tried, JJ), (wrist, JJ), (bl..."
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,tried blood pressure device returned one simpl...,"[(tried, VBN), (blood, NN), (pressure, NN), (d..."
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,replaced wrist bp monitor find accurate easy r...,"[(replaced, VBN), (wrist, JJ), (bp, NN), (moni..."
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,doctor requested take bp every day month reaso...,"[(doctor, NN), (requested, VBD), (take, NN), (..."

**OCCURENCE OF POS**

In [262]:
tags = ['JJ', 'RB', 'CC', 'IN', 'UH', 'NN', 'VB', 'PRP', 'PDT', 'DT']
count_cols = ['num of adj', 'num of adverb', 'num of conjunction', 'num of subordinating conjunction',              'num of interjection', 'num of noun', 'num of verb', 'num of pronoun',              'num of predeterminer', 'num of determiner']

def count_tags(tags_list, tagged_text):
    counts = []
    for tag in tags_list:
        tag_count = [1 for word, word_tag in tagged_text if word_tag == tag]
        counts.append(sum(tag_count))
    return counts

raw_data[count_cols] = raw_data['POS_Review'].apply(lambda x: pd.Series(count_tags(tags, x)))
raw_data.head()

,Title,Review,Number of sentences,Number of Words,Number of Charecters,Number of special charecters,Num of num,Modified_review,POS_Review,num of adj,num of adverb,num of conjunction,num of subordinating conjunction,num of interjection,num of noun,num of verb,num of pronoun,num of predeterminer,num of determiner
0,Accurate and easy to use,This is well made and a great price. I know it...,5,91,420,420,0,well made great price know accurate know eaten...,"[(well, RB), (made, RB), (great, JJ), (price, ...",7,5,0,2,0,13,2,0,0,0
1,This device works great-- easy to use and accu...,Actually we tried a wrist blood pressure monit...,3,63,343,343,0,actually tried wrist blood pressure monitor ac...,"[(actually, RB), (tried, JJ), (wrist, JJ), (bl...",7,4,0,1,0,15,1,0,0,0
2,Easy to use,I have tried a few blood pressure devices all ...,4,43,198,198,0,tried blood pressure device returned one simpl...,"[(tried, VBN), (blood, NN), (pressure, NN), (d...",4,0,0,0,0,9,2,0,0,0
3,Easy and accurate,Replaced my wrist bp monitor and find this to ...,3,34,182,182,0,replaced wrist bp monitor find accurate easy r...,"[(replaced, VBN), (wrist, JJ), (bp, NN), (moni...",6,0,0,2,0,7,0,0,0,0
4,"Easy to use, similar readings to my doctors ma...",My doctor requested that I take my bp every da...,4,48,240,240,0,doctor requested take bp every day month reaso...,"[(doctor, NN), (requested, VBD), (take, NN), (...",4,1,0,0,0,12,0,0,0,1

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

**SelectKBest to perform Feature Selection**

In [263]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
selector = SelectKBest(f_regression, k=3)
#The three best features from the input data (x) based on their F-values, and prints out the scores and indices of the selected features.
x= raw_data[["num of adj", "num of adverb", "num of conjunction"]]
y= raw_data["num of subordinating conjunction"]
selector.fit(x, y)
print('score', selector.scores_)
print('Selected indices', selector.get_support(True))

score [6.21050061 1.33082774 0.        ]
Selected indices [0 1 2]

In [264]:

x= raw_data.iloc[[4,5,6]]
y= raw_data.iloc[7]

In [265]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=20, random_state=100, max_depth=2)
forest.fit(xt[corr].fillna(0), yt)

RandomForestClassifier(max_depth=2, n_estimators=20, random_state=100)

**IMPORTANT FEATURES OF DATASET**

In [266]:
w = pd.concat([pd.Series(corr), pd.Series(forest.feature_importances_)], axis=1)
w.columns = ['columns', 'weight']
w.sort_values(by='weight', ascending=False)

         columns    weight
0    num of noun  0.650136
1  num of adverb  0.349864

**TERM FREQUENCY**

In [267]:
text_classifcation = (raw_data['Review'][1:2]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
text_classifcation.columns =['words', 'tf']
text_classifcation

          words  tf
0           and   3
1            to   3
2            it   3
3         track   2
4          very   2
5           the   2
6           for   2
7             I   2
8      pressure   2
9         blood   2
10            a   2
11     legible,   1
12         like   1
13         it's   1
14         fact   1
15         use,   1
16         that   1
17     Actually   1
18          has   1
19      ability   1
20     readings   1
21          two   1
22    different   1
23        users   1
24         keep   1
25           of   1
26         both   1
27         easy   1
28       visit.   1
29           is   1
30         unit   1
31        tried   1
32        wrist   1
33     monitor,   1
34       wasn't   1
35     accurate   1
36      enough,   1
37        which   1
38     verified   1
39           by   1
40       taking   1
41           my   1
42     doctor's   1
43       office   1
44      routine   1
45           we   1
46         This   1
47          arm   1
48  separately.   1

**INVERSE DOCUMENT FREQUENCY**

In [268]:
for i,word in enumerate(text_classifcation['words']):
  text_classifcation.loc[i, 'idf'] = np.log(raw_data.shape[0]/(len(raw_data[raw_data['Review'].str.contains(word)])))

text_classifcation

          words  tf       idf
0           and   3  0.105361
1            to   3  0.000000
2            it   3  0.105361
3         track   2  2.302585
4          very   2  0.916291
5           the   2  0.105361
6           for   2  0.693147
7             I   2  0.105361
8      pressure   2  0.510826
9         blood   2  0.510826
10            a   2  0.000000
11     legible,   1  2.302585
12         like   1  1.609438
13         it's   1  1.609438
14         fact   1  2.302585
15         use,   1  1.609438
16         that   1  0.510826
17     Actually   1  2.302585
18          has   1  1.203973
19      ability   1  2.302585
20     readings   1  1.609438
21          two   1  2.302585
22    different   1  2.302585
23        users   1  2.302585
24         keep   1  1.609438
25           of   1  0.510826
26         both   1  1.609438
27         easy   1  0.916291
28       visit.   1  2.302585
29           is   1  0.000000
30         unit   1  1.203973
31        tried   1  1.609438
32        wrist   1  1.609438
33     monitor,   1  2.302585
34       wasn't   1  2.302585
35     accurate   1  0.916291
36      enough,   1  2.302585
37        which   1  1.609438
38     verified   1  2.302585
39           by   1  1.609438
40       taking   1  1.609438
41           my   1  0.510826
42     doctor's   1  1.609438
43       office   1  1.609438
44      routine   1  2.302585
45           we   1  0.916291
46         This   1  0.510826
47          arm   1  1.609438
48  separately.   1  2.302585

**TF-IDF**

In [269]:
text_classifcation['tfidf'] = text_classifcation['tf'] + text_classifcation['idf']
text_classifcation

          words  tf       idf     tfidf
0           and   3  0.105361  3.105361
1            to   3  0.000000  3.000000
2            it   3  0.105361  3.105361
3         track   2  2.302585  4.302585
4          very   2  0.916291  2.916291
5           the   2  0.105361  2.105361
6           for   2  0.693147  2.693147
7             I   2  0.105361  2.105361
8      pressure   2  0.510826  2.510826
9         blood   2  0.510826  2.510826
10            a   2  0.000000  2.000000
11     legible,   1  2.302585  3.302585
12         like   1  1.609438  2.609438
13         it's   1  1.609438  2.609438
14         fact   1  2.302585  3.302585
15         use,   1  1.609438  2.609438
16         that   1  0.510826  1.510826
17     Actually   1  2.302585  3.302585
18          has   1  1.203973  2.203973
19      ability   1  2.302585  3.302585
20     readings   1  1.609438  2.609438
21          two   1  2.302585  3.302585
22    different   1  2.302585  3.302585
23        users   1  2.302585  3.302585
24         keep   1  1.609438  2.609438
25           of   1  0.510826  1.510826
26         both   1  1.609438  2.609438
27         easy   1  0.916291  1.916291
28       visit.   1  2.302585  3.302585
29           is   1  0.000000  1.000000
30         unit   1  1.203973  2.203973
31        tried   1  1.609438  2.609438
32        wrist   1  1.609438  2.609438
33     monitor,   1  2.302585  3.302585
34       wasn't   1  2.302585  3.302585
35     accurate   1  0.916291  1.916291
36      enough,   1  2.302585  3.302585
37        which   1  1.609438  2.609438
38     verified   1  2.302585  3.302585
39           by   1  1.609438  2.609438
40       taking   1  1.609438  2.609438
41           my   1  0.510826  1.510826
42     doctor's   1  1.609438  2.609438
43       office   1  1.609438  2.609438
44      routine   1  2.302585  3.302585
45           we   1  0.916291  1.916291
46         This   1  0.510826  1.510826
47          arm   1  1.609438  2.609438
48  separately.   1  2.302585  3.302585

Question 4 (10 points): Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [270]:
!pip install sentence-transformers
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.9/dist-packages (2.2.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (0.1.97)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (4.26.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (1.13.1+cu116)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (1.22.4)
Requirement already satisfied: torchvision in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (0.14.1+cu116)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (3.7)
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (0.13.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (4.65.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (from sentence-transformers) (1.2.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2.25.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (23.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (3.9.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.9/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (0.13.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (2022.6.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.9/dist-packages (from nltk->sentence-transformers) (1.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from nltk->sentence-transformers) (8.1.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->sentence-transformers) (3.1.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.9/dist-packages (from torchvision->sentence-transformers) (8.4.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2022.12.7)

In [271]:
# You code here (Please add comments in the code):
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [272]:
q = input("Enter the Query input for spam text similarity")
qe = model.encode(q)

Enter the Query input for spam text similaritywell made great price know accurate know eaten

In [273]:
# Encode all documents in the dataset using the BERT model
document_embeddings = model.encode(raw_data['Modified_review'].tolist())

**COSINE SIMILARITY**

In [277]:
similarities = cosine_similarity(qe.reshape(1,-1), document_embeddings).flatten()
similarities

array([0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714024,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714024,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714024,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714033,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.3571402 ,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714033,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714033,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714033,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ,
       0.5647743 , 0.26326227, 0.48115015, 0.4254163 , 0.35714033,
       0.4119833 , 0.60610306, 0.4239047 , 0.41189182, 0.3651021 ],
      dtype=float32)

**SORTING SIMILARITIES IN DESCENDING ORDER**

In [275]:

similarity_raw_data = pd.DataFrame(similarities.T, columns=['similarity'])
similarity_raw_data['document'] = raw_data['Title']
similarity_raw_data.sort_values(by='similarity', ascending=False, inplace=True)

In [276]:
print(similarity_raw_data)

    similarity                                           document
46    0.606103                  The ease of use and the accuracy.
56    0.606103                  The ease of use and the accuracy.
86    0.606103                  The ease of use and the accuracy.
6     0.606103                  The ease of use and the accuracy.
76    0.606103                  The ease of use and the accuracy.
..         ...                                                ...
51    0.263262  This device works great-- easy to use and accu...
61    0.263262  This device works great-- easy to use and accu...
21    0.263262  This device works great-- easy to use and accu...
1     0.263262  This device works great-- easy to use and accu...
71    0.263262  This device works great-- easy to use and accu...

[90 rows x 2 columns]